name: Test

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: hecrj/setup-rust-action@v2
        with:
          rust-version: nightly
      - name: Check Cargo availability
        run: cargo --version
      - name: Check Rustup default toolchain
        run: rustup default | grep nightly
      - name: Test
        run: |
          cargo test
